### ISSUE TITLE
Virus Reported in Binaries

### ISSUE THREAD

**Issue by johnco3** [lallousx86/ResetPermission#2]
Looks like the latest binary has been infected somehow. when I download the zip containing the repository Windows 10 defender stops and indicates:

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
containerfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\1A3174CC-5DC3-3F3D-928F-312AF424B25E_1d1c4c8307921b4
containerfile:D:\ProfileData\Downloads\ResetPermission-master.zip
file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\1A3174CC-5DC3-3F3D-928F-312AF424B25E_1d1c4c8307921b4
file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\1A3174CC-5DC3-3F3D-928F-312AF424B25E_1d1c4c8307921b4->ResetPermission-master/BIN/ResetPermission.zip->ResetPermission.exe
file:D:\ProfileData\Downloads\ResetPermission-master.zip->ResetPermission-master/BIN/ResetPermission.zip->ResetPermission.exe
webfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\1A3174CC-5DC3-3F3D-928F-312AF424B25E_1d1c4c8307921b4|https://codeload.github.com/lallousx86/ResetPermission/zip/master|chrome.exe
webfile:D:\ProfileData\Downloads\ResetPermission-master.zip|https://codeload.github.com/lallousx86/ResetPermission/zip/master|chrome.exe

**Comment by lallousx86** [comment]
This is a false positive. I double and triple checked the binary. I have filed a report to Windows Defender Team.

Please check here: https://www.virustotal.com/en/file/7930ebabda9987a5ecca7e11cc1c8dca094ba9ee74957c2ffa9b988637e764b3/analysis/

Only 17/57 as of 06/11/2016 false positively detect as a malware!

No need to worry. If you are concerned, just don't use the GUI version of this tool OR compile the program from the source code yourself.

Thanks for the report.

**Comment by lallousx86** [comment]
I have updated my blog post to make people aware of how shameful A/V software are.
